# Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.233
neo_version_range=[21,)
loader_version_range=[4,)

# Mod
mod_id=tfc_alloy_ext
mod_name=TFC Alloy Extension
mod_license=MIT
mod_version=0.0.1
mod_group_id=com.yukimods.alloyext
mod_authors=Coin0804
mod_description=TFC Alloy Extension — 劣等合金系统 & 熔铸炉集成

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
